"""empty message

Revision ID: 03637d5cd81e
Revises: 78cce2cbeef4
Create Date: 2026-03-03 01:43:43.917407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03637d5cd81e'
down_revision = '78cce2cbeef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_characters', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_characters_characters_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_characters_users_id_fkey', type_='foreignkey')
        batch_op.drop_column('users_id')
        batch_op.drop_column('characters_id')

    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_planets_planets_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_planets_users_id_fkey', type_='foreignkey')
        batch_op.drop_column('planets_id')
        batch_op.drop_column('users_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('planets_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('favorite_planets_users_id_fkey', 'users', ['users_id'], ['id'])
        batch_op.create_foreign_key('favorite_planets_planets_id_fkey', 'planets', ['planets_id'], ['id'])

    with op.batch_alter_table('favorite_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('characters_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('favorite_characters_users_id_fkey', 'users', ['users_id'], ['id'])
        batch_op.create_foreign_key('favorite_characters_characters_id_fkey', 'characters', ['characters_id'], ['id'])

    # ### end Alembic commands ###
