"""empty message

Revision ID: 15152377895e
Revises: 03637d5cd81e
Create Date: 2026-03-05 21:42:55.296815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15152377895e'
down_revision = '03637d5cd81e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_characters', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id_characters'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
